version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Make
          command: gcc -o puppol.buildrooms puppol.buildrooms.c
          
      - run:
            name: BuildRooms
            command: puppol.buildrooms
      
